name: MIN_ML
channels:
  - conda-forge
  - defaults
dependencies:
    - python
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - scipy         # Common math/stats/science functions
    - seaborn
    - flake8
    - pep8
    - scikit-learn
    - pathlib
    - pytorch
    - pip
    - pip:
        - pyrolite
        - PyIRoGlass