name: mineralML-RTD
channels:
    - conda-forge
    - pytorch
    - defaults
dependencies:
    - python=3.9
    - pandoc
    - pip
    - pip:
        - sphinx_rtd_theme>=0.5.0
        - ipython
        - sphinxcontrib-bibtex>=2.3.0
        - nbsphinx==0.8.12
        - ipykernel
        - matplotlib
        - numpy
        - pandas
        - scipy
        - seaborn
        - scikit-learn
        - torch
        - hdbscan
        - mineralML