name: mineralML-RTD
channels:
    - conda-forge
    - pytorch
    - defaults
dependencies:
    - python
    - pandoc
    - pip
    - pip:
        - sphinx_rtd_theme>=0.5.0
        - ipython
        - sphinxcontrib-bibtex>=2.3.0
        - sphinx<=8.1.0
        - nbsphinx==0.9.6
        - ipykernel
        - openpyxl
        - pandas
        - numpy
        - matplotlib
        - scikit-learn
        - scipy
        - seaborn
        - torch
        - hdbscan
        - mineralML